# Generated by Django 3.0.7 on 2020-06-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20200616_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='active_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='expire_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
