# Generated by Django 3.0.7 on 2020-06-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_auto_20200617_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='pay_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='pay_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='profiledetail',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pay_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
