# Generated by Django 3.0.7 on 2020-07-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetail',
            name='status_detail',
            field=models.CharField(choices=[('CURRENT', 'Actual'), ('RENOVATED', 'Renovado'), ('CANCELED', 'Cancelado')], default='CURRENT', max_length=20),
        ),
    ]
